### ISSUE TITLE
Targeting Images Google Colab

### ISSUE THREAD

**Issue by Chaumasaur** [rinongal/StyleGAN-nada#14]
Hi! I'm quite new when it comes to coding, and I've been struggling to do style targeting from a set of images on the colab. I've tried replacing the source class and target class options, but I only stumble upon a bunch of errors no matter what I do. Is that function not available yet on colab, or am I simply not understanding what I'm supposed to do correctly?

**Comment by rinongal** [comment]
Hey! Targeting specific image sets isn't currently supported on the Colab, but if you want to add it then the easiest place would be to modify the 'training_args' of step 3. Just look for the line that says 'target_img_list' (see image below) and change to None to a list of paths to your images (for example `"target_img_list": ['/content/target_images/img1.png', '/content/target_images/img2.jpg']`). 

You're also going to need to upload those files to Colab, but that's easily done by opening the files pane on the left and just dragging the files onto the UI.

Also keep in mind you're probably going to need to use more iterations (I'd start with ~1000 and reduce as needed).

![image](https://user-images.githubusercontent.com/19426368/131240972-cde93546-7a84-4e0e-a694-6d7d8ac2c85b.png)

If that still gives you trouble, let me know and I'll find the time to add full support for it over the coming week.

**Comment by Chaumasaur** [comment]
Hi, and sorry for the late reply! I got everything to work perfectly, so thank you so much for the help and no need to rush with adding any extra support. I'm curious as to how it works cause it seems much "smarter" than a classic style transfer, are you using CLIP to guide the style transfer as well? Otherwise I have no further questions or problems, and you're free to close the issue. Once again I really appreciate the help, big thanks!

**Comment by rinongal** [comment]
Happy to help!

And indeed we are using CLIP to guide the transfer! It's actually very similar to targeting domains using text.
The only difference is that we replace the text-described direction with the CLIP-space direction between the provided image set and the images creates by the original generator.

The intent was to allow a way to target styles which are difficult to describe using text, but I'm sure there are more fun ways to abuse it ;)

Will close the issue for now, but if you do have more questions feel free to open another issue or just send them my way!
