### ISSUE TITLE
no checkpoint save

### ISSUE THREAD

**Issue by ljiqy** [rinongal/StyleGAN-nada#2]
Hi, thanks for the excellent work!
I set save_interval: 50, but no checkpoint saved in output_dir

**Comment by rinongal** [comment]
Are you having this issue with the Collab, or with the offline training script?

If it's the Collab, you can add:

```
        if (args.save_interval is not None) and (i > 0) and (i % args.save_interval == 0):
            torch.save(
                {
                    "g_ema": net.generator_trainable.generator.state_dict(),
                    "g_optim": g_optim.state_dict(),
                },
                f"{ckpt_dir}/{str(i).zfill(6)}.pt",
            )
```
to the training loop. 

I'll update the Collab to add model saving support.

**Comment by rinongal** [comment]
Colab has been updated. Let me know if you're still having issues.

**Comment by ljiqy** [comment]
Thank you for your quick reply!
 I have this issue with the offline training script, I have change offline script according colab, and the issue have been solved, thank you!

**Comment by rinongal** [comment]
Happy to help. It doesn't look like the checkpoint code is missing from the train script, so I'm not sure what was causing your issue. Closing for now.
