### ISSUE TITLE
output PT format

### ISSUE THREAD

**Issue by smithee77** [rinongal/StyleGAN-nada#22]
Hi Rinongal, first of all many thanks for your amazing repo :)
I assume that generated .pt models under output/checkpoint folder are also in Pytorch Rosinality format, is it correct?
 Is there any way to transform them into "standard" Pytorch or Tensorflow format? 

Thanks again and sorry if it's off-topic
S.

**Comment by rinongal** [comment]
They are indeed in Pytorch Rosinality format, and unfortunately I'm not aware of a good way to convert them back.

However, if you're willing to do a bit of code-work, you can use the StyleGAN3 branch which I believe should be able to support StyleGAN2 and StyleGAN-ADA pkls with minor changes.

Let me know if you're willing to dive into that and I'll be happy to chat and tell you what needs to be changed (or if you want to wait, I can try getting around to it towards the end of November).

**Comment by smithee77** [comment]
Hi, the thing is I have some tools that uses either tensorflow or standard pytorch format, and I was praying to use them with nada-generated stuff for a project I'm working on :) . Many thanks, I'll keep an eye to your repo.

**Comment by rinongal** [comment]
To anyone stumbling across this issue, [this repo](https://github.com/eps696/stylegan2ada) has a tool for converting rosinality checkpoints back to an official .pkl format.
