### ISSUE TITLE
Error generating samples 

### ISSUE THREAD

**Issue by smithee77** [rinongal/StyleGAN-nada#23]
Hi again :)
Once I train a model, I'm trying to generate samples using not the "# Step 4: Generate samples with the new model", but the sample generator included in stylegan2-ada-rosinality cloned repo:
!python /content/stylegan_ada/generate.py --seeds 10,11 --network /content/output/checkpoint/000001.pt --outdir /content/

I'm getting this error when loading the file:

Loading networks from "/content/output/checkpoint/000001.pt"...
Traceback (most recent call last):
  File "/content/stylegan_ada/generate.py", line 121, in <module>
    main()
  File "/content/stylegan_ada/generate.py", line 116, in main
    generate_images(**vars(args))
  File "/content/stylegan_ada/generate.py", line 28, in generate_images
    _G, _D, Gs = pickle.load(fp)
**_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.**

I'm doing something wrong? Is it an error? Many thanks

**Comment by rinongal** [comment]
I'm not sure which repo you're talking about, but from the error it looks like the code you're running is trying to load a pickle checkpoint (probably in the format of the official checkpoints) and not the standard pytorch .pt format.

You should be able to generate images with our checkpoints using the stylegan2-pytorch implementation of rosinality. If you want to use pkls, see my response to issue #22

**Comment by smithee77** [comment]
Hi @rinongal thanks for your quick response.

I'm using notebook https://colab.research.google.com/github/rinongal/stylegan-nada/blob/main/stylegan_nada.ipynb
Using FTTH as base and with CLIP-driven training, I've generated a new model, saved as /content/output/checkpoint/000001.pt

With this result, I've tried to generate samples using both the generate.py file from both repos:
* https://github.com/NVlabs/stylegan2-ada/  
* https://github.com/rosinality/stylegan2-pytorch/

changing the line 59 of SETUP cell.

In both cases I got the same error running  

!python /content/stylegan_ada/generate.py --seeds 10,11 --network /content/output/checkpoint/000001.pt --outdir /content/

Probably it makes sense with the official repo, but with Rosinality's?

Thanks again

**Comment by rinongal** [comment]
That's odd. The error you posted is specifically failing in a pickle.load call, which doesn't exist in Rosinality's generate.py (he loads with torch.load).

His code also has a different set of arguments. I.e. there is no --seeds argument and he takes a path to a checkpoint with --ckpt and not with --network.

If you're running the command you posted as is in both directories then you're never actually runing Rosinality's version. You're calling the official one every time because you're using the full /content/stylegan_ada/generate.py path (rather than, for example, /content/stylegan2-pytorch/generate.py)

**Comment by smithee77** [comment]
Absolutely my mistake. I was using correct path (to Rosinality's generator) but standard repo arguments. Many thanks, closing issue
