### ISSUE TITLE
issue With Colab note book

### ISSUE THREAD

**Issue by ndparissos** [rinongal/StyleGAN-nada#27]
Hello,

Today when I I tried to run the 3rd step (training) of the Colab notebook I am getting the following error.  Could you please assist?

Loading base models...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-f2ac383c1fa1> in <module>()
     69 
     70 print("Loading base models...")
---> 71 net = ZSSGAN(args)
     72 print("Models loaded! Starting training...")
     73 

/content/stylegan_nada/ZSSGAN/model/ZSSGAN.py in __init__(self, args)
    154 
    155         # Set up frozen (source) generator
--> 156         self.generator_frozen = SG2Generator(args.frozen_gen_ckpt, img_size=args.size, channel_multiplier=args.channel_multiplier).to(self.device)
    157         self.generator_frozen.freeze_layers()
    158         self.generator_frozen.eval()

AttributeError: 'Namespace' object has no attribute 'channel_multiplier'

**Comment by rinongal** [comment]
Seems like I broke something with an update earlier today. I'll fix it asap. In the meanwhile you can add `"channel_multiplier": 2,` to the `training_args` list in step 3 and it should resolve it.

**Comment by rinongal** [comment]
There, it should be fixed. Let me know if you still have issues.

**Comment by ndparissos** [comment]
works now thank you very much!
