### ISSUE TITLE
How to fit stylegan3

### ISSUE THREAD

**Issue by wodsoe** [rinongal/StyleGAN-nada#28]
It's amazing!
Could you update to official stylegan2 and stylegan3?

**Comment by rinongal** [comment]
Thanks!

There's actually already a branch for StyleGAN3: https://github.com/rinongal/StyleGAN-nada/tree/StyleGAN3-NADA
It's not as stable and some features are missing, but you can give it a try.

No plans for adapting to the official StyleGAN2, but you might be able to get the SG3 branch to work with an official SG2 pkl.

**Comment by wodsoe** [comment]
Thank you!
