### ISSUE TITLE
StyleGAN how to generate B image using A source image

### ISSUE THREAD

**Issue by desires19** [rinongal/StyleGAN-nada#33]
Hi,

Thanks for sharing the great work.

I am studying the StyleGAN and it is new for me.

I want to know how to use StyleGAN to create a new B images from A images. I can change the input images for StyleGAN.

Any help would be really appreciated in solving this problem!

**Comment by rinongal** [comment]
Hi,

I'm not sure I understand what you're trying to do. Are you trying to convert images between different domains? Are you trying to edit some properties of an image (e.g. change the age of a person)? Are you trying to train a new model?

**Comment by desires19** [comment]
Thanks for your reply！

I am trying to edit some properites of an image, but I can't find how to input an image to the StyleGAN model

**Comment by desires19** [comment]
Tnanks for your help and advise!

**Comment by rinongal** [comment]
Happy to help. Closing this for now, but if you have any more questions feel free to re-open or open a new issue.
