### ISSUE TITLE
Black images on prediction

### ISSUE THREAD

**Issue by MAGLeb** [rinongal/StyleGAN-nada#35]
![image](https://user-images.githubusercontent.com/52084975/155076884-f1e9b262-b556-4c8c-ac67-e108d1c2c6df.png)
Net return for me only Nan.
![image](https://user-images.githubusercontent.com/52084975/155077586-e1c7519a-fe11-4535-952e-cd897d4041bc.png)

Maybe it is connected with converting sg2 model?
Also, it is really hard for me to set up the model locally. I had tried a lot of different ways.

**Comment by rinongal** [comment]
A few quick questions:

Are you using a custom StyleGAN2 model? 
Was it trained with StyleGAN2 or StyleGAN-ADA? And if it was trained with ADA, did you use the tensorflow or the pytorch version?

The conversion script also produces some images from both the original and the converted models, so you should be able to look at those images in the pretrained model directory and see if the conversion happened correctly.

About setting up locally, I'm going to need a few more details :)
What OS are you trying to run on? And what sorts of issues did you encounter? We also have a docker version in the readme that you can use to avoid having to set up an environment (though you'll have to set up nvidia-docker instead).

**Comment by MAGLeb** [comment]
_1. Are you using a custom StyleGAN2 model?_
I loaded models from github:
```
!git clone https://github.com/NVlabs/stylegan2-ada/ $stylegan_ada_dir
!git clone https://github.com/rinongal/stylegan-nada.git $stylegan_nada_dir
```
and also load model ffhq.pt with this part of code:
```
if not os.path.isfile(os.path.join(pretrained_model_dir, file_name)):
    print("Downloading chosen model...")

    if download_string.endswith(".pkl"):
        !wget $download_string -O $pretrained_model_dir/$file_name
    else:
        downloader.download_file(download_string, os.path.join(pretrained_model_dir, file_name))
```
In addition, I did every step in the notebook.


_2. Environment_
I use docker environment: nvcr.io/nvidia/pytorch:21.10-py3
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000001:00:00.0 Off |                    0 |
| N/A   49C    P0    57W / 149W |      0MiB / 11441MiB |     99%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
_3. We also have a docker version in the readme that you can use to avoid having to set up an environment (though you'll have to set up nvidia-docker instead)._
Thank you. I will try use docker later. If you could help me with the notebook, I will appreciate it.

**Comment by MAGLeb** [comment]
_"The conversion script also produces some images from both the original and the converted models, so you should be able to look at those images in the pretrained model directory and see if the conversion happened correctly."_

Conversion script? Do you mean this part of the code?
```
if not os.path.isfile(os.path.join(pretrained_model_dir, pt_file_name)):
    print("Converting sg2 model. This may take a few minutes...")
    
    tf_path = next(filter(lambda x: "tensorflow" in x, sys.path), None)
    py_path = tf_path + f":{stylegan_nada_dir}/ZSSGAN"
    convert_script = os.path.join(stylegan_nada_dir, "convert_weight.py")
    !PYTHONPATH=$py_path python $convert_script --repo $stylegan_ada_dir --gen $pretrained_model_dir/$file_name
```

This part of the code did not execute because of the if condition.

**Comment by rinongal** [comment]
Conversion script: I was asking because you asked:

> Maybe it is connected with converting sg2 model?

in the original post. If you're using FFHQ then there's indeed no need to convert anything and that part of the code shouldn't execute.

About the notebook: 

Could you try generating images without fine-tuning the model? You should be able to do that by setting the number of training iterations to 0 and then running both the training block and the generation block (steps 3 and 4).

Did you change anything about the code itself in section 3?

**Comment by MAGLeb** [comment]
Set up the number of training iterations to 0 and run both steps.
![image](https://user-images.githubusercontent.com/52084975/155109080-0df9cc8a-743f-46b2-a21d-1b35e3703e5b.png)

**Comment by rinongal** [comment]
Alright. So it looks like you're having issues already at the generation step and before we even do any training.
I'm not sure what the problem could be, but I suspect it might just be some pytorch / cuda version issue.

I tried looking up similar issues in Rosinality's repo. There are two that might be related:
https://github.com/rosinality/stylegan2-pytorch/issues/214
https://github.com/rosinality/stylegan2-pytorch/issues/60
However, if you didn't modify my code then you're using 'cuda' as the device and not 'cuda:0', and this issue should not arise.

Maybe something else that seems strange in your screenshots: your warning output says you're using PyTorch 1.10.2+cu102, but your nvidia-smi screenshot lists cuda 11.4 so there might be some mismatch there.

Did the UI in our docker work for you? If it does, then the environment there is working fine and you can probably just set up your notebook inside that docker instead?
