### ISSUE TITLE
Docker image old version of code

### ISSUE THREAD

**Issue by MAGLeb** [rinongal/StyleGAN-nada#36]
Am I right that in the docker container old version of the code? 
Try to pass images to train the model, but the result is different. Model does not use images to train.

**Comment by MAGLeb** [comment]
And of course different results between the google collab model and the docker model. 
COLLAB
![image](https://user-images.githubusercontent.com/52084975/156930712-e94b531a-b6ce-4757-9a7a-e677cc7697f2.png)
DOCKER
![image](https://user-images.githubusercontent.com/52084975/156930723-8faf0d1c-380c-4b5c-ad43-4151ffc211a6.png)
Same parameters.

**Comment by rinongal** [comment]
Which docker are you using? The one from replicate, or the one from our own docker repo?

**Comment by MAGLeb** [comment]
The second one. Use the command `docker-compose up` in the StyleGan directory for creating an image.

**Comment by rinongal** [comment]
Just an update that I haven't forgotten you, but it's a rather busy week due to conference deadlines. I'll probably be freer around the weekend and I'll try to look into things.

**Comment by MAGLeb** [comment]
Thank you. I am waiting. If I can help you, I am at your disposal.

**Comment by rinongal** [comment]
Okay, so the docker does make use of older code. It should still have support for image directory targeting, but the notebook inside the docker doesn't support this option. 

The quickest solution to get things up-to-date is to just git pull/clone inside the docker. 
It has the correct environment set up (and you've been able to run the code inside it), so the new code should work fine as well.

A second alternative is to use the docker from [replicate.com](https://replicate.com/rinongal/stylegan-nada) which is more up-to-date. You can grab it with:
`docker pull r8.im/rinongal/stylegan-nada@sha256:5295deb56da56f890f123e1bb0ede34d63896adf42d6c4856defdca2b187552a`
This version is slightly bigger since it also has some pre-trained models inside for inference. It doesn't have all the initial models from other domains though.

Finally, I can update the docker, but that's going to take me a bit of time since I've got a few other things on my table atm.

We can start by seeing if option 1 works for you. If it doesn't then we can try the other two.

**Comment by MAGLeb** [comment]
> Finally, I can update the docker, but that's going to take me a bit of time since I've got a few other things on my table atm.

Thank you for your answer. Yeah of cause. I will try the first two options and let you know.

**Comment by MAGLeb** [comment]
Tried first case, install a new version of the stylegan_naga repository
I have been stuck on saving the model.
```
torch.save(model, path)

Traceback (most recent call last):
  File "train.py", line 55, in <module>
    train()
  File "train.py", line 36, in train
    model.save(model_name)
  File "/workspace/style-transfer/model_gan.py", line 45, in save
    torch.save(model_wrapper, path)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object '_transform.<locals>.<lambda>'

type(model)
# <class 'ZSSGAN.model.ZSSGAN.ZSSGAN'>
```

Try to figure out the reason for the problem but unsuccessfully. 
Also in the docker instant from [replica](https://replicate.com/rinongal/stylegan-nada), I saw that you saved the model in a different way than I do. 

The next step try to use docker instant.

**Comment by MAGLeb** [comment]
Also, one more example of training the model with parameters:
- source class "Photo"
- target class "Monet portrait"
- iteration 200

That was in your paper:
![image](https://user-images.githubusercontent.com/52084975/159002592-6d74c223-0617-43d0-8d16-e1cfc6896c62.png)

In docker container:
![image](https://user-images.githubusercontent.com/52084975/159001874-a9b38e77-0271-4ab2-bb17-2b7669e1882e.png)

But I had very good results with:
- sketch
![image](https://user-images.githubusercontent.com/52084975/159002793-17d763c4-3bfd-4d18-9b7d-80288c3864fa.png)

- Ukiyo
![image](https://user-images.githubusercontent.com/52084975/159002860-2c2d6753-0b18-4f19-ac0e-cc03d67771e0.png)

- White walker
![image](https://user-images.githubusercontent.com/52084975/159002964-b7756c33-3f3e-4d2c-b9c1-386c425a3d11.png)

- Werewolf
![image](https://user-images.githubusercontent.com/52084975/159003262-e281b420-2e1d-4f89-9c04-e06e556d1c9b.png)

**Comment by rinongal** [comment]
An immediate guess is that there's some difference between the parameters you're using and the ones in the Colab. 

Your ukiyo-e / white walker / werewolf results also look nothing like I'd expect. Mostly the color scheme. 
Can you check what the training outputs look like? Are they similar to your own editing results, or closer to mine?

If it's the later, then you're probably not loading the model correctly.

About saving - just see what I'm doing in my code. You want to save the generator itself. You don't need the rest of the ZSSGAN module.

**Comment by rinongal** [comment]
I tried running the prompts again the colab and I'm not encountering your issue. In some of the other issues / in our paper, we list the parameters used for specific prompts. You can try reproducing the results with those parameters and this might give us a better idea of whether parameter differences are at fault or not.

**Comment by MAGLeb** [comment]
Thanks so much. I refreshed the Style-Gan repository and saved the model in your way (saved only generator) and everything works fine. Also start to investigate your paper to understand which parameters are related to the results.
