### ISSUE TITLE
Latend code generation

### ISSUE THREAD

**Issue by lebeli** [rinongal/StyleGAN-nada#40]
I am trying to provide my own latent code for the "generate_videos.py" skript. I am using ReStyle for generating the latent code from my own pictures. When I start the skript everything is fine for the first 120 frames. After that every image is composed by multiple compressed random images. Is this a common issue?

If validated the latent code I am using. The shape of my latent code is identical to the shape of the latent code you provided. I noticed though, that the range of values of my own latent code is much greater that yours. Do you scale the values produced by ReStyle? Could this be the source of the error?

The skript works just fine for the latent code that you provided.

**Comment by rinongal** [comment]
Our sample latents were generated with StyleFlow which might be the cause of the difference. Can you try using the ReStyle implementation in our Colab notebook just to double check that you get similar numbers to your own implementation?

Regardless, can you share an example of the results you're getting? If your outputs contain multiple images it sounds more like a dimensionality issue. Maybe some of your codes do have an additional dimension / larger batch size? This would explain why this issue only crops up after about 120 frames.

**Comment by lebeli** [comment]
I double checked the shape of the latent code and you were right, there was a dimension missing: (18, 512) vs. (1, 18, 512). Thank you very much for your quick reply.
