### ISSUE TITLE
Directional loss without templates

### ISSUE THREAD

**Issue by dnl-trpp** [rinongal/StyleGAN-nada#41]
Hi all. I noticed that by default the prompts that will be used to compute the text direction are composed based on a template. This generates a lot of directions and the mean is then used. This behaviour is not documented in the paper, am I missing something? Can I obtain the same results by only using two prompts (source and target) like described originally?

**Comment by rinongal** [comment]
Hey,

We added the templates following their use in StyleCLIP (which motivate them through the improved classification accuracy these templates give in the original CLIP paper). In practice I can't really say the difference was meaningful. You should be able to remove them with minimal or no impact on results.

**Comment by dnl-trpp** [comment]
I'm experimenting without the templates and can confirm thay they have very little impact on the results! Thank you and awsome project by the way.
