### ISSUE TITLE
Question about directional loss implementation.

### ISSUE THREAD

**Issue by Victarry** [rinongal/StyleGAN-nada#43]
Thank you for your great work and I really like it.

One of the problems occurred to me is what's the purpose of normalizing `edit_direction`, since the directional loss is actually cosine similarity which will normalize the compared feature. And in my experiment, it shows almost the same visual results.

https://github.com/rinongal/StyleGAN-nada/blob/1a17364d7eeaea853cc4262b4972d2cd66c70d06/ZSSGAN/criteria/clip_loss.py#L181
And I also noticed some of the normalization used `.clone.norm()` while others did not. What's the difference of its effects?

**Comment by rinongal** [comment]
Normalization: 

If you'll look at our directional loss class, you'll see that we actually tried other (non cosine-similarity) alternatives, which do not automatically normalize. If you're always using the cosine similarity then you can certainly drop this step (but don't drop the normalizations in the image feature / text feature extraction functions)

Clones:

It's a dirty way to enable the divide and assign operator ('/=') when the tensor involved requires gradients. We use it as an alternative to `edit_direction = edit_direction / edit_direction.norm(dim=-1, keepdim=True)`. I didn't bother profiling the two alternatives and seeing if the clone has a noticeable impact on memory consumption / run times, but I'd be surprised if that was the case.

The situations where we don't clone (e.g. text directions) don't require gradients to begin with, so there's no pytorch limitation to just using '/=' with the same tensor on both sides.

**Comment by Victarry** [comment]
Got it, thanks for your response.
