### ISSUE TITLE
Size of output.

### ISSUE THREAD

**Issue by MAGLeb** [rinongal/StyleGAN-nada#45]
Right now the size of the output is 1024x1024 pixels. Can I change the size of the output?

**Comment by rinongal** [comment]
In what sense are you trying to change the size of the output? If you have a pre-trained model with another output size, you can use the --size argument to tell the model to expect this alternative size. If you're asking whether a pre-trained 1024x1024 model can be used to produce images of other resolutions - the answer is no. You'll have to resize the output yourself. For decreasing resolution you can probably just work with PIL's resize. If you want to increase resolution, I'd have a look at super resolution models like ESRGAN.

**Comment by MAGLeb** [comment]
I really appreciate your help here!

I looked through the closed issues and found some tips about the quality of images, increasing iterations, and decreasing learning_rate. Also, tried to use the ESRGAN model, and the resolution is increased but the quality and blur effect remained the same.
