### ISSUE TITLE
Question with quantitative evaluation on image diversity

### ISSUE THREAD

**Issue by jone1222** [rinongal/StyleGAN-nada#46]
Hello Rinongal,

As far as I know, you mentioned that you clustered around generated images using K-medoids since yours does not use a training set.
How did you set the number of clusters K?  (the few-shot adaptation methods choose K to be the number of training samples)

Can I ask you to provide details on evaluating image diversity quantitatively? If you can provide the source code for quantitative evaluation, I would be grateful. Thanks.

**Comment by rinongal** [comment]
Hi jone,

We used 10 clusters to align with the level of supervision that the most recent methods at the time (Ojha et al.) were aimed at. 

Regarding the code, here's my current uncommented file: [eval_diversity.txt](https://github.com/rinongal/StyleGAN-nada/files/8610236/eval_diversity.txt)
It's based on [Ojha's code](https://github.com/utkarshojha/few-shot-gan-adaptation/blob/main/feat_cluster.py). 

You can flip between the k_med and data-centered versions by just commenting out the lines at the bottom (and commenting out the kmeds version). Let me know if you have any issues with it and I'll try to help / clean up the script.
