### ISSUE TITLE
Training on Colab error for StyleGan2

### ISSUE THREAD

**Issue by Muhammad-Ahmad-Ghani** [rinongal/StyleGAN-nada#48]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-f03880abd276>](https://localhost:8080/#) in <module>()
----> 1 from ZSSGAN.model.ZSSGAN import ZSSGAN
      2 
      3 import numpy as np
      4 
      5 import torch

[/content/stylegan_nada/ZSSGAN/model/ZSSGAN.py](https://localhost:8080/#) in <module>()
     15 from ZSSGAN.model.sg2_model import Generator, Discriminator
     16 from ZSSGAN.criteria.clip_loss import CLIPLoss
---> 17 import ZSSGAN.legacy as legacy
     18 
     19 def requires_grad(model, flag=True):

ModuleNotFoundError: No module named 'ZSSGAN.legacy'

**Comment by rinongal** [comment]
Thanks for the heads up. Should be fixed. Let me know if there's still an issue.
