### ISSUE TITLE
Sample Code for retraining OASIS

### ISSUE THREAD

**Issue by vionwinnie** [rinongal/StyleGAN-nada#56]
Hi I am wondering if you can release the code for adapting StyleGAN-nada training method to retrain OASIS? Thanks

**Comment by rinongal** [comment]
Hi,

We haven't cleaned up the Oasis code and weren't planning to upload it, but if you send me an e-mail (to rinong at gmail dot com) I'll send you a zip with the current version.

(Same holds for anyone running across this issue in the future :) )

**Comment by rinongal** [comment]
As the code has been sent, I'm closing this. Let me know if you need more help.
