### ISSUE TITLE
Problems trying to convert the sg2 model

### ISSUE THREAD

**Issue by xXLeoXxOne** [rinongal/StyleGAN-nada#7]
I am currently trying to run the program and I need to convert the ffhq.pkl model do a .pt one.

When I enter `python stylegan_nada\convert_weight.py --repo stylegan_ada --gen models/ffhq.pkl` it says:

`Traceback (most recent call last):
  File "stylegan_nada\convert_weight.py", line 11, in <module>
    from ZSSGAN.model.sg2_model import Generator, Discriminator
  File "C:\Users\msk4x\Documents\Projekte\stylegan\stylegan_nada\ZSSGAN\sg2_model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix`
    
How can I fix this?

**Comment by rinongal** [comment]
Hi,

For a quick workaround you can just use the colab notebook and convert the FFHQ model using the script there. The result will be in the models folder.

That said, you seem to be failing on the part that imports some of StyleGAN2's compiled cuda ops - this might be a problem when you try to actually train the model as well. Can you post the full error so I can see what exactly fails?

**Comment by xXLeoXxOne** [comment]
Yeah thought of the colab workaround already, takes ages to download tho.

I will post another comment after I tried to train it.

**Comment by xXLeoXxOne** [comment]
Umm now I get this error...


C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py:109: UserWarning: File C:\Users\msk4x/.cache/clip\ViT-B-32.pt is not a JIT archive. Loading as a state dict instead
  warnings.warn(f"File {model_path} is not a JIT archive. Loading as a state dict instead")
Traceback (most recent call last):
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 104, in load
    model = torch.jit.load(model_path, map_location=device if jit else "cpu").eval()
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 275, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError:

aten::_convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool benchmark, bool deterministic, bool cudnn_enabled) -> (Tensor):
Expected at most 12 arguments but found 13 positional arguments.
:
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py(420): _conv_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py(423): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/root/workspace/multimodal-pytorch/multimodal/model/multimodal_transformer.py(85): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/root/workspace/multimodal-pytorch/multimodal/model/multimodal_transformer.py(221): visual_forward
/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py(940): trace_module
<ipython-input-1-40b054242c5d>(36): export_torchscript_models
<ipython-input-2-808c11c4d1cf>(3): <module>
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3418): run_code
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3338): run_ast_nodes
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3147): run_cell_async
/opt/conda/lib/python3.7/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2923): _run_cell
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2878): run_cell
/opt/conda/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py(555): interact
/opt/conda/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py(564): mainloop
/opt/conda/lib/python3.7/site-packages/IPython/terminal/ipapp.py(356): start
/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py(845): launch_instance
/opt/conda/lib/python3.7/site-packages/IPython/__init__.py(126): start_ipython
/opt/conda/bin/ipython(8): <module>
Serialized   File "code/__torch__/torch/nn/modules/conv/___torch_mangle_9366.py", line 8
  def forward(self: __torch__.torch.nn.modules.conv.___torch_mangle_9366.Conv2d,
    input: Tensor) -> Tensor:
    x = torch._convolution(input, self.weight, None, [32, 32], [0, 0], [1, 1], False, [0, 0], 1, False, False, True, True)
        ~~~~~~~~~~~~~~~~~~ <--- HERE
    return x
  def forward1(self: __torch__.torch.nn.modules.conv.___torch_mangle_9366.Conv2d,


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stylegan_nada.py", line 166, in <module>
    net = ZSSGAN(args)
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in __init__
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in <dictcomp>
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\criteria\clip_loss.py", line 36, in __init__
    self.model, clip_preprocess = clip.load(clip_model, device=self.device)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 111, in load
    state_dict = torch.load(model_path, map_location="cpu")
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named '__torch__'

**Comment by xXLeoXxOne** [comment]
After downloading the .pt model from colab I now get this error:

`Loading base models...
100%|███████████████████████████████████████| 354M/354M [00:36<00:00, 9.79MiB/s]
C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py:109: UserWarning: File C:\Users\msk4x/.cache/clip\ViT-B-32.pt is not a JIT archive. Loading as a state dict instead
  warnings.warn(f"File {model_path} is not a JIT archive. Loading as a state dict instead")
Traceback (most recent call last):
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 104, in load
    model = torch.jit.load(model_path, map_location=device if jit else "cpu").eval()
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 275, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError:

aten::_convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool benchmark, bool deterministic, bool cudnn_enabled) -> (Tensor):
Expected at most 12 arguments but found 13 positional arguments.
:
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py(420): _conv_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py(423): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/root/workspace/multimodal-pytorch/multimodal/model/multimodal_transformer.py(85): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/root/workspace/multimodal-pytorch/multimodal/model/multimodal_transformer.py(221): visual_forward
/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py(940): trace_module
<ipython-input-1-40b054242c5d>(36): export_torchscript_models
<ipython-input-2-808c11c4d1cf>(3): <module>
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3418): run_code
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3338): run_ast_nodes
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3147): run_cell_async
/opt/conda/lib/python3.7/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2923): _run_cell
/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2878): run_cell
/opt/conda/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py(555): interact
/opt/conda/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py(564): mainloop
/opt/conda/lib/python3.7/site-packages/IPython/terminal/ipapp.py(356): start
/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py(845): launch_instance
/opt/conda/lib/python3.7/site-packages/IPython/__init__.py(126): start_ipython
/opt/conda/bin/ipython(8): <module>
Serialized   File "code/__torch__/torch/nn/modules/conv/___torch_mangle_9366.py", line 8
  def forward(self: __torch__.torch.nn.modules.conv.___torch_mangle_9366.Conv2d,
    input: Tensor) -> Tensor:
    x = torch._convolution(input, self.weight, None, [32, 32], [0, 0], [1, 1], False, [0, 0], 1, False, False, True, True)
        ~~~~~~~~~~~~~~~~~~ <--- HERE
    return x
  def forward1(self: __torch__.torch.nn.modules.conv.___torch_mangle_9366.Conv2d,


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stylegan_nada.py", line 166, in <module>
    net = ZSSGAN(args)
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in __init__
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in <dictcomp>
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\criteria\clip_loss.py", line 36, in __init__
    self.model, clip_preprocess = clip.load(clip_model, device=self.device)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 111, in load
    state_dict = torch.load(model_path, map_location="cpu")
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named '__torch__'`

**Comment by xXLeoXxOne** [comment]
With another torch version it doesnt get this far...

Loading base models...
Traceback (most recent call last):
  File "stylegan_nada.py", line 166, in <module>
    net = ZSSGAN(args)
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in __init__
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in <dictcomp>
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\criteria\clip_loss.py", line 36, in __init__
    self.model, clip_preprocess = clip.load(clip_model, device=self.device)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 133, in load
    model.apply(patch_device)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 445, in apply
    module.apply(fn)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 445, in apply
    module.apply(fn)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 446, in apply
    fn(self)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 130, in patch_device
    if "value" in node.attributeNames() and str(node["value"]).startswith("cuda"):
TypeError: 'torch._C.Node' object is not subscriptable

**Comment by xXLeoXxOne** [comment]
Trying with 1.8.1 now because pip warns me that clip requires 1.8.1

**Comment by rinongal** [comment]
You could also try taking a look at: https://github.com/openai/CLIP/issues/79
The latest CLIP should work fine with 1.9 as well.

**Comment by xXLeoXxOne** [comment]
Already saw that

I upgraded to the recommended version (1.8.1) and now I get this:

Traceback (most recent call last):
  File "stylegan_nada.py", line 166, in <module>
    net = ZSSGAN(args)
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in __init__
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in <dictcomp>
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\criteria\clip_loss.py", line 36, in __init__
    self.model, clip_preprocess = clip.load(clip_model, device=self.device)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 133, in load
    model.apply(patch_device)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 473, in apply
    module.apply(fn)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 473, in apply
    module.apply(fn)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 473, in apply
    module.apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 474, in apply
    fn(self)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 124, in patch_device
    graphs = [module.graph] if hasattr(module, "graph") else []
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\jit\_script.py", line 449, in graph
    return self._c._get_method("forward").graph
RuntimeError: Method 'forward' is not defined.

**Comment by xXLeoXxOne** [comment]
With the jit=False fix (trying ViT-B/32 now):

100%|███████████████████████████████████████| 256M/256M [00:28<00:00, 9.01MiB/s]
Traceback (most recent call last):
  File "stylegan_nada.py", line 166, in <module>
    net = ZSSGAN(args)
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in __init__
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\model\ZSSGAN.py", line 174, in <dictcomp>
    for model_name in args.clip_models}
  File "stylegan_nada\ZSSGAN\criteria\clip_loss.py", line 36, in __init__
    self.model, clip_preprocess = clip.load(clip_model, device=self.device, jit=False)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\clip-1.0-py3.6.egg\clip\clip.py", line 100, in load
    raise RuntimeError(f"Model {name} not found; available models = {available_models()}")
RuntimeError: Model ViT-B/16 not found; available models = ['RN50', 'RN101', 'RN50x4', 'ViT-B/32']

**Comment by xXLeoXxOne** [comment]
ViT-B/32 doesnt get this far tho...

**Comment by xXLeoXxOne** [comment]
Okay ViT-B/32 gets further now

Models loaded! Starting training...
Traceback (most recent call last):
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\notebook.py", line 96, in status_printer
    pbar = IProgress(min=0, max=total)
NameError: name 'IProgress' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stylegan_nada.py", line 191, in <module>
    for i in notebook.tqdm(range(args.iter)):
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\notebook.py", line 209, in __init__
    self.fp, total, self.desc, self.ncols)
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\notebook.py", line 104, in status_printer
    "FloatProgress not found. Please update jupyter and ipywidgets."
ImportError: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
Exception ignored in: <bound method tqdm.__del__ of   0%|<bar/>| 0/151 [00:00<?, ?it/s]>
Traceback (most recent call last):
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\std.py", line 1086, in __del__
    self.close()
  File "C:\Users\msk4x\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\notebook.py", line 245, in close
    self.sp(bar_style='danger')
AttributeError: 'tqdm_notebook' object has no attribute 'sp'

**Comment by xXLeoXxOne** [comment]
ViT-B/32 might be the fix, will have to fix an issue related to tqdm

**Comment by xXLeoXxOne** [comment]
WORKS NOW!!

Thank you!

I have a few questions about the program itself... (I am pretty new to this stuff and very interested in trying it out)

How does it "know" all of these target classes?
Can I somehow output 512/1024 images instead of 256?

**Comment by rinongal** [comment]
Regarding the ViT-B/16 error - that means you don't have the most up-to-date version of CLIP. You can run fine without it for most things though, so it's no biggie.

The way it 'knows' all the target classes is through CLIP - it's a model that was trained on ~400M images and associated text labels from the internet, and it learned to match images with texts that describe them. We're using that model in order to guide the training.

Outputs at 512/1024: The size of the outputs you get during training depends only on the resolution of the model you started with. If you're using a 1024x1024 FFHQ model, you're going to get 1024x1024 images.
If you want to generate them after the fact, you can look at the colab for an example of a function that does it. Everything up until display part is still using the full resolution of the model.

**Comment by xXLeoXxOne** [comment]
Okay thanks!
Is there any way to speed up importing everything?

**Comment by xXLeoXxOne** [comment]
It runs without any errors now but somehow the network doesnt get trained (the samples always look the same)... could that be because of jit=False and the ViT-B/32 instead of ViT-B/16?

**Comment by xXLeoXxOne** [comment]
I installed clip via pip install git+https://github.com/openai/CLIP.git so it should be the latest one, right?

**Comment by rinongal** [comment]
It will be the latest one, assuming you installed it in the last 26 days. If you had a version beforehand, then no. You can try to uninstall and install it again.

What texts are you using? Try something simple from our examples to make sure things are working correctly. Photo -> Sketch should be a good one.

ViT-B/32 should be enough for most changes. The ViT-B/16 version just helps with more local details.

I don't think jit=False is the problem since the newer CLIP versions (for example the one in the colab notebook) have it as a default, and the notebook works fine.

On speeding up imports - are you talking about the notebooks, or locally? If locally - first run takes a bit of extra time because it compiles some CUDA operations on the fly (and possibly downloads new CLIP models), but that only happens once and after that it should be quicker.

**Comment by xXLeoXxOne** [comment]
just using person -> zombie
Worked on the colab at least

**Comment by rinongal** [comment]
Can you paste the parameters you're using?
And which FFHQ model did you use? The official 1024x1024 one?

**Comment by xXLeoXxOne** [comment]
I will just post my whole code (converted the notebook and then changed some stuff)...
I am using the official one in the notebook

**Comment by xXLeoXxOne** [comment]
```
import os
import sys

pretrained_model_dir = os.path.join("", "models")
os.makedirs(pretrained_model_dir, exist_ok=True)
restyle_dir = os.path.join("", "restyle")
stylegan_ada_dir = os.path.join("", "stylegan_ada")
stylegan_nada_dir = os.path.join("", "stylegan_nada")
output_dir = os.path.join("", "output")
output_model_dir = os.path.join(output_dir, "models")
output_image_dir = "images/results/"
sys.path.append(restyle_dir)
sys.path.append(stylegan_nada_dir)
sys.path.append(os.path.join(stylegan_nada_dir, "ZSSGAN"))

from argparse import Namespace
import numpy as np
from PIL import Image
from tqdm import tqdm
import torch
import torchvision.transforms as transforms
from restyle.utils.common import tensor2im
from restyle.models.psp import pSp
from restyle.models.e4e import e4e
from ZSSGAN.model.ZSSGAN import ZSSGAN
import numpy as np
from ZSSGAN.utils.file_utils import save_images
from ZSSGAN.utils.training_utils import mixing_noise

device = 'cuda'

source_model_type = 'ffhq' #@param['ffhq', 'cat', 'dog', 'church', 'horse', 'car']

source_model_download_path = {"ffhq":   "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/ffhq.pkl",
                              "cat":    "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/afhqcat.pkl",
                              "dog":    "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/afhqdog.pkl",
                              "church": "1iDo5cUgbwsJEt2uwfgDy_iPlaT-lLZmi",
                              "car":    "1i-39ztut-VdUVUiFuUrwdsItR--HF81w",
                              "horse":  "1irwWI291DolZhnQeW-ZyNWqZBjlWyJUn"}

model_names = {"ffhq":   "ffhq.pkl",
               "cat":    "afhqcat.pkl",
               "dog":    "afhqdog.pkl",
               "church": "stylegan2-church-config-f.pkl",
               "car":    "stylegan2-car-config-f.pkl",
               "horse":  "stylegan2-horse-config-f.pkl"}

download_string = source_model_download_path[source_model_type]
file_name = model_names[source_model_type]
pt_file_name = file_name.split(".")[0] + ".pt"

dataset_sizes = {
    "ffhq":   1024,
    "cat":    512,
    "dog":    512,
    "church": 256,
    "horse":  256,
    "car":    512,
}

if not os.path.isfile(os.path.join(pretrained_model_dir, file_name)):
    print("Pls download "+file_name)
    exit()
        
if not os.path.isfile(os.path.join(pretrained_model_dir, pt_file_name)):
    convert_script = os.path.join(stylegan_nada_dir, "convert_weight.py")
    print("Enter this command: "+'python '+convert_script+' --repo '+stylegan_ada_dir+' --gen '+pretrained_model_dir+'/'+file_name+'( This might take a few minutes)')
    exit()

encoder_type = 'psp' #@param['psp', 'e4e']

restyle_experiment_args = {
    "model_path": os.path.join(pretrained_model_dir, f"restyle_{encoder_type}_ffhq_encode.pt"),
    "transform": transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.ToTensor(),
        transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])])
}

model_path = restyle_experiment_args['model_path']
ckpt = torch.load(model_path, map_location='cpu')

opts = ckpt['opts']

opts['checkpoint_path'] = model_path
opts = Namespace(**opts)

restyle_net = (pSp if encoder_type == 'psp' else e4e)(opts)

restyle_net.eval()
restyle_net.cuda()
print('Model successfully loaded!')

print("Loaded stuff!")

#training

print("Training parameters")

source_class = input("Source class? ")
target_class = input("Target class? ")

improve_shape = False

model_choice = ["ViT-B/32", "ViT-B/32"]
model_weights = [1.0, 0.0]

if improve_shape:
    model_weights[1] = 1.0
    
mixing = 0.9 if improve_shape else 0.0

auto_layers_k = int(2 * (2 * np.log2(dataset_sizes[source_model_type]) - 2) / 3) if improve_shape else 0
auto_layer_iters = 1 if improve_shape else 0

training_iterations = int(input("Iterations? "))
output_interval     = 50
save_interval       = 0

training_args = {
    "size": dataset_sizes[source_model_type],
    "batch": 2,
    "n_sample": 4,
    "output_dir": output_dir,
    "lr": 0.002,
    "frozen_gen_ckpt": os.path.join(pretrained_model_dir, pt_file_name),
    "train_gen_ckpt": os.path.join(pretrained_model_dir, pt_file_name),
    "iter": training_iterations,
    "source_class": source_class,
    "target_class": target_class,
    "lambda_direction": 1.0,
    "lambda_patch": 0.0,
    "lambda_global": 0.0,
    "lambda_texture": 0.0,
    "lambda_manifold": 0.0,
    "auto_layer_k": auto_layers_k,
    "auto_layer_iters": auto_layer_iters,
    "auto_layer_batch": 8,
    "output_interval": 50,
    "clip_models": model_choice,
    "clip_model_weights": model_weights,
    "mixing": mixing,
    "phase": None,
    "sample_truncation": 0.7,
    "save_interval": save_interval
}

args = Namespace(**training_args)

print("Loading base models...")
net = ZSSGAN(args)
print("Models loaded! Starting training...")

g_reg_ratio = 4 / 5

g_optim = torch.optim.Adam(
    net.generator_trainable.parameters(),
    lr=args.lr * g_reg_ratio,
    betas=(0 ** g_reg_ratio, 0.99 ** g_reg_ratio),
)

sample_dir = os.path.join(args.output_dir, "sample")
ckpt_dir   = os.path.join(args.output_dir, "checkpoint")

os.makedirs(sample_dir, exist_ok=True)
os.makedirs(ckpt_dir, exist_ok=True)

seed = 3

torch.manual_seed(seed)
np.random.seed(seed)

fixed_z = torch.randn(args.n_sample, 512, device=device)

for i in tqdm(range(args.iter)):
    net.train()
        
    sample_z = mixing_noise(args.batch, 512, args.mixing, device)

    [sampled_src, sampled_dst], clip_loss = net(sample_z)

    net.zero_grad()
    clip_loss.backward()

    g_optim.step()

    if i % output_interval == 0:
        net.eval()

        with torch.no_grad():
            [sampled_src, sampled_dst], loss = net([fixed_z], truncation=args.sample_truncation)

            if source_model_type == 'car':
                sampled_dst = sampled_dst[:, :, 64:448, :]

            grid_rows = 4

            save_images(sampled_dst, sample_dir, "dst", grid_rows, i)

            img = Image.open(os.path.join(sample_dir, f"dst_{str(i).zfill(6)}.jpg")).resize((1024, 256))
    
    if (args.save_interval > 0) and (i > 0) and (i % args.save_interval == 0):
        torch.save(
            {
                "g_ema": net.generator_trainable.generator.state_dict(),
                "g_optim": g_optim.state_dict(),
            },
            f"{ckpt_dir}/{str(i).zfill(6)}.pt",
        )


print("Now the fun part...")


#editing real images

def run_alignment(image_path):
    import dlib
    from scripts.align_faces_parallel import align_face
    if not os.path.exists("shape_predictor_68_face_landmarks.dat"):
        print('Downloading files for aligning face image...')
        os.system('wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2')
        os.system('bzip2 -dk shape_predictor_68_face_landmarks.dat.bz2')
        print('Done.')
    predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")
    aligned_image = align_face(filepath=image_path, predictor=predictor) 
    print("Aligned image has shape: {}".format(aligned_image.size))
    return aligned_image

def get_avg_image(net):
    avg_image = net(net.latent_avg.unsqueeze(0),
                    input_code=True,
                    randomize_noise=False,
                    return_latents=False,
                    average_code=True)[0]
    avg_image = avg_image.to('cuda').float().detach()
    return avg_image

while 1:

    image_path = input("Image name? (exit to exit and train to train new model) ")

    image_path_no_extension = image_path.split('.',2)[0]

    if image_path=="exit":
        break
    if image_path=="train":
        continue

    try:

        image_path = "images/"+image_path
        
        original_image = Image.open(image_path).convert("RGB")

        input_image = run_alignment(image_path)

        img_transforms = restyle_experiment_args['transform']
        transformed_image = img_transforms(input_image)

        opts.n_iters_per_batch = 5
        opts.resize_outputs = False

        from restyle.utils.inference_utils import run_on_batch

        with torch.no_grad():
            avg_image = get_avg_image(restyle_net)
            result_batch, result_latents = run_on_batch(transformed_image.unsqueeze(0).cuda(), restyle_net, opts, avg_image)

        inverted_latent = torch.Tensor(result_latents[0][4]).cuda().unsqueeze(0).unsqueeze(1)

        with torch.no_grad():
            net.eval()
            
            [sampled_src, sampled_dst] = net(inverted_latent, input_is_latent=True)[0]
            joined_img = torch.cat([sampled_src, sampled_dst], dim=0)
            save_images(joined_img,output_image_dir , "joined", 2, 0)
    except IOError:
        print("File not found")
    except UnboundLocalError:
        print("Face not found")
            

```

**Comment by rinongal** [comment]
Give me a few minutes, bringing up the colab to try and run with those parameters and check.

**Comment by xXLeoXxOne** [comment]
I reinstalled CLIP and there still is no ViT-B/16. Also reinstalled torch1.7.1 and there is no difference to before.

**Comment by rinongal** [comment]
Ok, found your issue.

In the model choice lines, replace your current code with just:

model_choice = ["ViT-B/32"]
model_weights = [1.0]

On getting the version with ViT-B/16 - please make sure it's not re-installing from your local cache.
The clip model isn't mine, it's OpenAIs, and since the colab notebook is able to get ViT-B/16 I don't think there's any issue on their end.

**Comment by xXLeoXxOne** [comment]
Wow, thanks!

**Comment by xXLeoXxOne** [comment]
Works now :)

**Comment by xXLeoXxOne** [comment]
If I would save the models (or are they called checkpoints?) after training them, how much storage space do they take?

**Comment by xXLeoXxOne** [comment]
Oh and how to I "retrain" the model to something else after training it? What variable to I have to delete (or do I need to unload torch?) so that there actually is a fresh model?

**Comment by rinongal** [comment]
FFHQ 1024x1024 are about 300 MB per checkpoint.

Retraining with something else - initializing a new network from scratch should be good enough. If you're working with a notebook, make sure you re-run all cells starting from the one where you define the args and do net = ZSSGAN(args).

**Comment by xXLeoXxOne** [comment]
Thank you for your time and your nice answers! Got the retraining working by restructuring some of my code... I might add a feature that saves the checkpoints after training and then loads them instead of training new ones (if I would want to use the same classes again)

**Comment by snow1929** [comment]
> I am currently trying to run the program and I need to convert the ffhq.pkl model do a .pt one.
> 
> When I enter `python stylegan_nada\convert_weight.py --repo stylegan_ada --gen models/ffhq.pkl` it says:
> 
> `Traceback (most recent call last): File "stylegan_nada\convert_weight.py", line 11, in <module> from ZSSGAN.model.sg2_model import Generator, Discriminator File "C:\Users\msk4x\Documents\Projekte\stylegan\stylegan_nada\ZSSGAN\sg2_model.py", line 11, in <module> from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix`
> 
> How can I fix this?

I fix it by changing the import path in sg2_model.py
from 
```
from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
``` 
to 
```
from ZSSGAN.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
```
