### ISSUE TITLE
Generate interpolation videos from trained models

### ISSUE THREAD

**Issue by samuelpietri** [rinongal/StyleGAN-nada#8]
I was wondering whether there's a possibility to share a script to generate videos from the trained model as shown on your project page. The .pt format is not easily usable for exporting videos from the original NVidia implementation. Any suggestion on how to implement it would be of much help.

**Comment by rinongal** [comment]
Sure. We don't have it unified as a single script at this point, so I'll have to create one - but I don't think it will be an issue. 
I'll add it to the to-do list and hopefully get around to it during the weekend.

**Comment by parthrangarajan** [comment]
Hey! Where will we be able to find the 'align_faces_parallel' script?
I am talking with respect to this line  `from scripts.align_faces_parallel import align_face` in the `run_alignment` function present in the google colab.

**Comment by rinongal** [comment]
That script (and most of the inversion code) is part of [ReStyle](https://github.com/yuval-alaluf/restyle-encoder).

**Comment by rinongal** [comment]
@samuelpietri I added a video generation script. It still requires you to supply your own initial and edited latent codes (or use the ones I uploaded as an example). Let me know if you need help with that.

**Comment by rinongal** [comment]
It has been more than a month since the video generation script was uploaded so I'm going to go ahead and close this. Feel free to re-open if you still need something.
